### ISSUE TITLE
Icon Aspect Ratio

### ISSUE THREAD

**Issue by makiftutuncu** [ergenekonyigit/salyangoz-electron#1]
Loved the idea!

However, on my MacBook Late 2013 15" Retina, the icon looks like this:
![screenshot 2016-06-15 10 49 35](https://cloud.githubusercontent.com/assets/1009191/16071968/f041827c-32e6-11e6-890d-5ef6d9a80f67.png)

It looks like a simple aspect ratio problem.

**Comment by ergenekonyigit** [comment]
Thanks 👍🏼 Fixed problem 😃
